### PR TITLE
Add UTM parameters to data

### PR DESCRIPTION
**Pull request by roborourke**
Adds a random configuration of UTM parameters to 40% of traffic data.

Fixes https://github.com/humanmade/altis-demo/issues/29

### CODE REVIEW

**Review by jazzsequence — COMMENTED** [review]
This looks good from the code level, but testing locally, I was unable to get any demo data to come in. My audiences don't have any data.

Screen Shot 2021-03-03 at 3 11 54 PM

**Comment by roborourke** [comment]
That’s possibly a separate issue then? Did the import run smoothly and were you able to see analytics data in kibana? There is a short term cache on audience data

**Comment by roborourke** [comment]
I think I know why, the php error logs would have shown a fatal because the maths package I made a separate PR for was missing. Once you’ve updated to add that it should all be good. This is what would’ve blocked the data being imported too.

**Comment by roborourke** [comment]
Gonna move ahead with this as time is a factor.

**Pull request merged**
